/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as EndpointProviderSlugRouteImport } from './routes/endpoint/$providerSlug'
import { Route as HealthLiveRouteImport } from './routes/health/live'
import { Route as HealthReadyRouteImport } from './routes/health/ready'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as AuthenticatedApiKeysIndexRouteImport } from './routes/_authenticated/api-keys/index'
import { Route as AuthenticatedConnectionsIndexRouteImport } from './routes/_authenticated/connections/index'
import { Route as AuthenticatedPlaygroundIndexRouteImport } from './routes/_authenticated/playground/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPlaygroundConnectionIdRouteImport } from './routes/api/playground/$connectionId'
import { Route as EndpointProviderSlugSplatRouteImport } from './routes/endpoint/$providerSlug/$'
import { Route as OauthClientMetadataConnectionIdRouteImport } from './routes/oauth/client-metadata.$connectionId'
import { Route as ApiPlaygroundConnectionIdSplatRouteImport } from './routes/api/playground/$connectionId/$'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointProviderSlugRoute = EndpointProviderSlugRouteImport.update({
  id: '/endpoint/$providerSlug',
  path: '/endpoint/$providerSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthLiveRoute = HealthLiveRouteImport.update({
  id: '/health/live',
  path: '/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/health/ready',
  path: '/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApiKeysIndexRoute =
  AuthenticatedApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConnectionsIndexRoute =
  AuthenticatedConnectionsIndexRouteImport.update({
    id: '/connections/',
    path: '/connections/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlaygroundIndexRoute =
  AuthenticatedPlaygroundIndexRouteImport.update({
    id: '/playground/',
    path: '/playground/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaygroundConnectionIdRoute =
  ApiPlaygroundConnectionIdRouteImport.update({
    id: '/api/playground/$connectionId',
    path: '/api/playground/$connectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EndpointProviderSlugSplatRoute =
  EndpointProviderSlugSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => EndpointProviderSlugRoute,
  } as any)
const OauthClientMetadataConnectionIdRoute =
  OauthClientMetadataConnectionIdRouteImport.update({
    id: '/oauth/client-metadata/$connectionId',
    path: '/oauth/client-metadata/$connectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlaygroundConnectionIdSplatRoute =
  ApiPlaygroundConnectionIdSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => ApiPlaygroundConnectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/endpoint/$providerSlug': typeof EndpointProviderSlugRouteWithChildren
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/playground/$connectionId': typeof ApiPlaygroundConnectionIdRouteWithChildren
  '/endpoint/$providerSlug/$': typeof EndpointProviderSlugSplatRoute
  '/oauth/client-metadata/$connectionId': typeof OauthClientMetadataConnectionIdRoute
  '/api-keys/': typeof AuthenticatedApiKeysIndexRoute
  '/connections/': typeof AuthenticatedConnectionsIndexRoute
  '/playground/': typeof AuthenticatedPlaygroundIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/playground/$connectionId/$': typeof ApiPlaygroundConnectionIdSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/endpoint/$providerSlug': typeof EndpointProviderSlugRouteWithChildren
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/playground/$connectionId': typeof ApiPlaygroundConnectionIdRouteWithChildren
  '/endpoint/$providerSlug/$': typeof EndpointProviderSlugSplatRoute
  '/oauth/client-metadata/$connectionId': typeof OauthClientMetadataConnectionIdRoute
  '/api-keys': typeof AuthenticatedApiKeysIndexRoute
  '/connections': typeof AuthenticatedConnectionsIndexRoute
  '/playground': typeof AuthenticatedPlaygroundIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/api/playground/$connectionId/$': typeof ApiPlaygroundConnectionIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/endpoint/$providerSlug': typeof EndpointProviderSlugRouteWithChildren
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/playground/$connectionId': typeof ApiPlaygroundConnectionIdRouteWithChildren
  '/endpoint/$providerSlug/$': typeof EndpointProviderSlugSplatRoute
  '/oauth/client-metadata/$connectionId': typeof OauthClientMetadataConnectionIdRoute
  '/_authenticated/api-keys/': typeof AuthenticatedApiKeysIndexRoute
  '/_authenticated/connections/': typeof AuthenticatedConnectionsIndexRoute
  '/_authenticated/playground/': typeof AuthenticatedPlaygroundIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/playground/$connectionId/$': typeof ApiPlaygroundConnectionIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/docs'
    | '/api/openapi.json'
    | '/endpoint/$providerSlug'
    | '/health/live'
    | '/health/ready'
    | '/oauth/callback'
    | '/api/auth/$'
    | '/api/playground/$connectionId'
    | '/endpoint/$providerSlug/$'
    | '/oauth/client-metadata/$connectionId'
    | '/api-keys/'
    | '/connections/'
    | '/playground/'
    | '/settings/'
    | '/api/playground/$connectionId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/docs'
    | '/api/openapi.json'
    | '/endpoint/$providerSlug'
    | '/health/live'
    | '/health/ready'
    | '/oauth/callback'
    | '/'
    | '/api/auth/$'
    | '/api/playground/$connectionId'
    | '/endpoint/$providerSlug/$'
    | '/oauth/client-metadata/$connectionId'
    | '/api-keys'
    | '/connections'
    | '/playground'
    | '/settings'
    | '/api/playground/$connectionId/$'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/setup'
    | '/_authenticated/docs'
    | '/api/openapi.json'
    | '/endpoint/$providerSlug'
    | '/health/live'
    | '/health/ready'
    | '/oauth/callback'
    | '/_authenticated/'
    | '/api/auth/$'
    | '/api/playground/$connectionId'
    | '/endpoint/$providerSlug/$'
    | '/oauth/client-metadata/$connectionId'
    | '/_authenticated/api-keys/'
    | '/_authenticated/connections/'
    | '/_authenticated/playground/'
    | '/_authenticated/settings/'
    | '/api/playground/$connectionId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  EndpointProviderSlugRoute: typeof EndpointProviderSlugRouteWithChildren
  HealthLiveRoute: typeof HealthLiveRoute
  HealthReadyRoute: typeof HealthReadyRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPlaygroundConnectionIdRoute: typeof ApiPlaygroundConnectionIdRouteWithChildren
  OauthClientMetadataConnectionIdRoute: typeof OauthClientMetadataConnectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoint/$providerSlug': {
      id: '/endpoint/$providerSlug'
      path: '/endpoint/$providerSlug'
      fullPath: '/endpoint/$providerSlug'
      preLoaderRoute: typeof EndpointProviderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/live': {
      id: '/health/live'
      path: '/health/live'
      fullPath: '/health/live'
      preLoaderRoute: typeof HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/health/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/api-keys/': {
      id: '/_authenticated/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof AuthenticatedApiKeysIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connections/': {
      id: '/_authenticated/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof AuthenticatedConnectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/playground/': {
      id: '/_authenticated/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof AuthenticatedPlaygroundIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playground/$connectionId': {
      id: '/api/playground/$connectionId'
      path: '/api/playground/$connectionId'
      fullPath: '/api/playground/$connectionId'
      preLoaderRoute: typeof ApiPlaygroundConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoint/$providerSlug/$': {
      id: '/endpoint/$providerSlug/$'
      path: '/$'
      fullPath: '/endpoint/$providerSlug/$'
      preLoaderRoute: typeof EndpointProviderSlugSplatRouteImport
      parentRoute: typeof EndpointProviderSlugRoute
    }
    '/oauth/client-metadata/$connectionId': {
      id: '/oauth/client-metadata/$connectionId'
      path: '/oauth/client-metadata/$connectionId'
      fullPath: '/oauth/client-metadata/$connectionId'
      preLoaderRoute: typeof OauthClientMetadataConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playground/$connectionId/$': {
      id: '/api/playground/$connectionId/$'
      path: '/$'
      fullPath: '/api/playground/$connectionId/$'
      preLoaderRoute: typeof ApiPlaygroundConnectionIdSplatRouteImport
      parentRoute: typeof ApiPlaygroundConnectionIdRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedApiKeysIndexRoute: typeof AuthenticatedApiKeysIndexRoute
  AuthenticatedConnectionsIndexRoute: typeof AuthenticatedConnectionsIndexRoute
  AuthenticatedPlaygroundIndexRoute: typeof AuthenticatedPlaygroundIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedApiKeysIndexRoute: AuthenticatedApiKeysIndexRoute,
  AuthenticatedConnectionsIndexRoute: AuthenticatedConnectionsIndexRoute,
  AuthenticatedPlaygroundIndexRoute: AuthenticatedPlaygroundIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface EndpointProviderSlugRouteChildren {
  EndpointProviderSlugSplatRoute: typeof EndpointProviderSlugSplatRoute
}

const EndpointProviderSlugRouteChildren: EndpointProviderSlugRouteChildren = {
  EndpointProviderSlugSplatRoute: EndpointProviderSlugSplatRoute,
}

const EndpointProviderSlugRouteWithChildren =
  EndpointProviderSlugRoute._addFileChildren(EndpointProviderSlugRouteChildren)

interface ApiPlaygroundConnectionIdRouteChildren {
  ApiPlaygroundConnectionIdSplatRoute: typeof ApiPlaygroundConnectionIdSplatRoute
}

const ApiPlaygroundConnectionIdRouteChildren: ApiPlaygroundConnectionIdRouteChildren =
  {
    ApiPlaygroundConnectionIdSplatRoute: ApiPlaygroundConnectionIdSplatRoute,
  }

const ApiPlaygroundConnectionIdRouteWithChildren =
  ApiPlaygroundConnectionIdRoute._addFileChildren(
    ApiPlaygroundConnectionIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  EndpointProviderSlugRoute: EndpointProviderSlugRouteWithChildren,
  HealthLiveRoute: HealthLiveRoute,
  HealthReadyRoute: HealthReadyRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPlaygroundConnectionIdRoute: ApiPlaygroundConnectionIdRouteWithChildren,
  OauthClientMetadataConnectionIdRoute: OauthClientMetadataConnectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
